<?php
	
	$token = $_GET["token"];
	if($token != 'Euxqk6F9j2c9KGrjD8mtf8oU9IA7cmZM'){
		exit();
	}

	//here we define system usage report array
	$system_usage = [];
	
	//cpu usage
	$stat1 = file('/proc/stat'); 
	sleep(1); 
	$stat2 = file('/proc/stat'); 
	$info1 = explode(" ", preg_replace("!cpu +!", "", $stat1[0])); 
	$info2 = explode(" ", preg_replace("!cpu +!", "", $stat2[0])); 
	$dif = array(); 
	$dif['user'] = $info2[0] - $info1[0]; 
	$dif['nice'] = $info2[1] - $info1[1]; 
	$dif['sys'] = $info2[2] - $info1[2]; 
	$dif['idle'] = $info2[3] - $info1[3]; 
	$total = array_sum($dif); 
	$cpu = array(); 
	foreach($dif as $x=>$y) $cpu[$x] = round($y / $total * 100, 1);
	$system_usage['CPU'] = $cpu['user'];

	//RAM usage
	$free = shell_exec('free');
	$free = (string)trim($free);
	$free_arr = explode("\n", $free);
	$mem = explode(" ", $free_arr[1]);
	$mem = array_filter($mem);
	$mem = array_merge($mem);
	$memory_usage = $mem[2]/$mem[1]*100;
	$system_usage['RAM'] = $memory_usage;

	//hdd usage
	$mountedDirectory = "/";
	$dts = disk_total_space($mountedDirectory );
	$dfs = disk_free_space($mountedDirectory );
	$usedPercent = round(($dts - $dfs) / $dts * 100)."%";
	$system_usage['HDD'] = $usedPercent;
	
	$str   = @file_get_contents('/proc/uptime');
	$num   = floatval($str);
	$secs  = fmod($num, 60); $num = (int)($num / 60);
	$mins  = $num % 60;      $num = (int)($num / 60);
	$hours = $num % 24;      $num = (int)($num / 24);
	$days  = $num;
	$system_usage['UPTIME'] = 'days:'.$days;

	// Path to the JSON file generated by the Bash script
	$json_file = 'online_users.json';

	// Read and decode the JSON data
	$json_data = file_get_contents($json_file);
	$users = json_decode($json_data, true);

	// Remove 'sshd' and empty values
	$filtered_users = array_filter($users, function($user) {
		return !empty($user) && $user !== 'sshd' && $user !== 'root';
	});

	// Re-index the array after filtering
	$filtered_users = array_values($filtered_users);

	//here we can 
	$system_usage['ONLINE_USERS'] = count($filtered_users);

	// Output the result as JSON
	echo json_encode($system_usage);
?>
