<?php

	// Path to the JSON file generated by the Bash script
	$json_file = 'online_users.json';

	// Read and decode the JSON data
	$json_data = file_get_contents($json_file);
	$users = json_decode($json_data, true);

	// Remove 'sshd' and empty values
	$filtered_users = array_filter($users, function($user) {
		return !empty($user) && $user !== 'sshd' && $user !== 'root';
	});

	// Re-index the array after filtering
	$filtered_users = array_values($filtered_users);

	// Count the unique active SSH users
	$system_usage['ONLINE_USERS_LIST'] = $filtered_users;

	// Output the result as JSON
	echo json_encode($system_usage);
?>
